### ISSUE TITLE
Jenkins Pipeline example

### ISSUE THREAD

**Issue by ysb33r** [gradle-guides/executing-gradle-builds-on-jenkins#1]
This can do with an example of using Jenkins pipelines. 

At this stage I think it will will still need to usin a conditional switch in the pipeline to either use gradlew or gradlew.bat because IIRC the Grasel plugin in Jenkins has nto received enough love of late to be fully pipeline ready.

**Comment by eriwen** [comment]
Fully agreed. Is this something you'd be willing to draft @ysb33r?

CC @wolfs for your awareness about possible Jenkins Gradle plugin issues for pipelines.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #248](https://github.com/gradle/guides/issues/248) via [**ZenHub**](https://www.zenhub.com/)
