### ISSUE TITLE
Task :signArchives FAILED

### ISSUE THREAD

**Issue by jasonwzhu** [gradle-guides/executing-gradle-builds-on-jenkins#3]
I am following the guide at this location 
https://guides.gradle.org/executing-gradle-builds-on-jenkins/
checked out and ran ".gradlew build", but with the following errors:

> Task :signArchives FAILED
gpg: no default secret key: No secret key
gpg: signing failed: No secret key

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signArchives'.
> Process 'command 'gpg2'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
8 actionable tasks: 8 executed

Publishing build scan...
https://gradle.com/s/yhv2m3ekov4ju

**Comment by a-hahn** [comment]
I also have have Task ;signArchives FAILED with the demo, it seems the gpg2 is missing in docker on jenkins. So the example doesn't run out of the box.

> Starting a Gradle Daemon (subsequent builds will be faster)

> Task :discoverMainScriptsExtensions

> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :pluginDescriptors
> Task :processResources
> Task :classes
> Task :inspectClassesForKotlinIC
> Task :jar
> Task :sourcesJar
> Task :signArchives FAILED

> FAILURE: Build failed with an exception.

> * What went wrong:
> Execution failed for task ':signArchives'.
> A problem occurred starting process command gpg2

> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log > output. Run with --scan to get full insights.

**Comment by mmoser18** [comment]
Same here. Any new wisdom on that? What are we missing?
I am observing such issues with about 50% of all Gradle projects. :-( Guess, we need to wait for Gradle's successor to see really stable builds. :-(

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #276](https://github.com/gradle/guides/issues/276) via [**ZenHub**](https://www.zenhub.com/)
