### ISSUE TITLE
The hostname 'scans-in.gradle.com' could not be resolved.

### ISSUE THREAD

**Issue by mmoser18** [gradle-guides/executing-gradle-builds-on-jenkins#9]
After commenting the signing part the build succeeds but uploading the produced scan fails with the subject error message. It seems that such scan-uploads are not supported anymore.

The error message reads:
...
BUILD SUCCESSFUL in 32s
13 actionable tasks: 7 executed, 6 up-to-date
Publishing build scan...

A network error occurred.

The hostname 'scans-in.gradle.com' could not be resolved.
You may be disconnected from the Internet.

If you require assistance with this problem, please report it via https://gradle.com/scans/help/plugin and include the following information via copy/paste.
```
----------
Gradle version: 5.4.1
Plugin version: 2.2.1
Request URL: https://scans-in.gradle.com/in/5.4.1/2.2.1
Request ID: ad6a12ea-f721-484e-a2d3-f18bbde1bbe5
Exception: java.net.UnknownHostException: scans-in.gradle.com
----------
```

But trying to do that yields, that this site doesn't exist anymore, either. It gets redirected after maybe 10 seconds to https://gradle.com/help/ but there is nothing to find there on the topic of scans and uploads.

So, I guess this whole tutorial is obsolete. A pity... :-(

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #287](https://github.com/gradle/guides/issues/287) via [**ZenHub**](https://www.zenhub.com/)
